/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ViCollapse {
        "title": string;
        "toggle": () => Promise<void>;
    }
    interface ViComponent1 {
        "text": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLViCollapseElement extends Components.ViCollapse, HTMLStencilElement {
    }
    var HTMLViCollapseElement: {
        prototype: HTMLViCollapseElement;
        new (): HTMLViCollapseElement;
    };
    interface HTMLViComponent1Element extends Components.ViComponent1, HTMLStencilElement {
    }
    var HTMLViComponent1Element: {
        prototype: HTMLViComponent1Element;
        new (): HTMLViComponent1Element;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "vi-collapse": HTMLViCollapseElement;
        "vi-component-1": HTMLViComponent1Element;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ViCollapse {
        "title"?: string;
    }
    interface ViComponent1 {
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "vi-collapse": ViCollapse;
        "vi-component-1": ViComponent1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "vi-collapse": LocalJSX.ViCollapse & JSXBase.HTMLAttributes<HTMLViCollapseElement>;
            "vi-component-1": LocalJSX.ViComponent1 & JSXBase.HTMLAttributes<HTMLViComponent1Element>;
        }
    }
}
